### ISSUE TITLE
Multiple actions fail

### ISSUE THREAD

**Issue by raphaelokon** [mzur/kirby-uniform#100]
Hi there … I have only one of two actions working and sending the mail.

I have the following controller: 

```php
…
'actions' => array(
                array(
                    '_action' => 'email',
                    'to' => (string) $page->email(),
                    'sender' => 'mail@tld.de',
                    'subject' => 'Test 1',
                    'message' => 'Message from Test 1'
                ),
                array(
                    '_action' => 'email',
                    'to' => 'another@tld.de',
                    'sender' => 'mail@tld.de',
                    'subject' => 'Test 2'
                )
            )
```

Here, only the second action gets sent. `$form->hasMessage()` is true after submit but `$form->successful()`  returns nothing instead of either `success` or `error`. Any clues?

**Comment by raphaelokon** [comment]
Reason I am doing this is that I want to send a confirmation to the submitter. Is there any example how to achieve this? Thanks.

**Comment by mzur** [comment]
So you want `$page->email()` to be the email address of the user who submitted the form? `$page->email()` is not what you want, since it returns the content of the email field of the _page_ containing the form, which is always the same, and not the content of the email field of the submitted form. You have two options to send confirmation emails to the submitter of the form:

You can use the [`_receive_copy`](https://github.com/mzur/kirby-uniform/wiki/Action:-Email) field of the email action.

Else, you can access the form data with the `get()` Kirby helper, so you could do something like this to send a second email to the submitter of the form:

```php
array(
   '_action' => 'email',
   'to' => get('_from'),
   'sender' => 'mail@tld.de',
   'subject' => 'Test 2'
)
```

You probably want to use another email snippet for the confirmation, too. It's all on the wiki page of the email action :wink:

**Comment by raphaelokon** [comment]
Thanks! Yep I found that out myself. I missed the wiki entirely :D

**Comment by raphaelokon** [comment]
@mzur BTW: Does the `get()` needs additional escaping/sanitization?

**Comment by mzur** [comment]
The helper uses [stripslashes](https://github.com/getkirby/toolkit/blob/48567b8523725b322b0b5b19727bec88eae2c8b9/lib/str.php#L588) of the Toolkit so you should be fine for the email address. For other uses (like storing data in a file) you might use [esc](https://getkirby.com/docs/toolkit/api/helpers/esc) as well.
