### ISSUE TITLE
Honeypot hiding method

### ISSUE THREAD

**Issue by mciszczon** [mzur/kirby-uniform#109]
I was wondering, whether there is a better way to visually hide honeypot from the user. This are the current styles for it:

```
.uniform__potty {
	position: absolute;
	top: -9999px;
	left: -9999px;
}
```

Althought I am not 100% sure, I think giving the honeypot element these styles may force the browser to actually draw a box that is ~9999px wide and tall. And of course, this is a performance issue.

Wouldn't the boilerplate `visuallyhidden` class work just as well?

```
.visuallyhidden { 
	position: absolute; 
	overflow: hidden; 
	clip: rect(0 0 0 0); 
	height: 1px; width: 1px; 
	margin: -1px; padding: 0; border: 0; 
}
```

**Comment by mzur** [comment]
Sure you are totally free to use whatever CSS you like to hide the form field. You are not required to use the provided CSS, not even to hide the form field. If you already use the boilerplate CSS, just replace the `uniform__potty` class with `visuallyhidden`. With Uniform v3 you can use the helper function like this: `honeypot_field(null, 'visallyhidden')`.

The `uniform__potty` class doesn't cause the browser to draw a 9999 px box, though. It just moves the input element 9999 px to the left and 9999 px to the top so it is no longer visible. The dimensions of the input element stay the same. [CSS-Tricks](https://css-tricks.com/places-its-tempting-to-use-display-none-but-dont/) mentions both techniques and I believe there are tons of others that work, too. I'd rather leave the `uniform__potty` class as it is because it is trivial for developers to change it if they like.

**Comment by mciszczon** [comment]
Yeah, I just wanted to point it out, it's easy to change.

 As I mentioned, I am not sure, but there was also a similar technique to do image-replacement with `text-indent: 9999px`. This technique worked fine, but the downside to this technique is that it has a performance hit as the browser will draw a giant 9999px box offscreen.

I think that something similar may be happening here. If not, then it's fine. Personally, I'll stick to the `.visuallyhidden` class.

Thank you very much for the attention to the issue. And for this great plugin, of course. Keep up the good work! Greetings.
