### ISSUE TITLE
The 'email' field is stripped from the email body

### ISSUE THREAD

**Issue by lekkerduidelijk** [mzur/kirby-uniform#122]
Thanks again @mzur for the great plugin.

Just a small question: when I use `<input name="email">` and submit the form the 'email' field doesn't show in the message body.

Why is this?

Cheers!

**Comment by mzur** [comment]
The field is [stripped](https://github.com/mzur/kirby-uniform/blob/477a6037b6855d27fefa37b70e68d4193483cca8/src/Actions/EmailAction.php#L114) from the body by default because the email address is present in the `Reply-To` header of the email. If you want to include it in the body as well you have to create a custom email snippet.

**Comment by lekkerduidelijk** [comment]
Ok, totally clear to me.
