### ISSUE TITLE
.htaccess rules break submission

### ISSUE THREAD

**Issue by HashandSalt** [mzur/kirby-uniform#134]
I have these rules in my `.htaccess` to strip www, force https and add a trailing slash on the url. Unfortunately its preventing form submission. If i leave the form empty and hit submit, the page reloads and no error message is displayed. If i complete the form correctly, the page reloads, no success message is displayed and the form does not send an email.

My form action looks like this:

`<form class="form" id="hireus" action="<?= $page->url()?>#hireus" method="post">`

The `.htaccess` rules:

```
RewriteCond %{HTTP_HOST} ^www\. [NC,OR]
RewriteCond %{HTTPS} off
RewriteCond %{HTTP_HOST} ^(?:www\.)?(.+)$ [NC]
RewriteRule ^ https://%1%{REQUEST_URI} [R=301,L,NE]

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !(.*)/$
RewriteCond %{REQUEST_FILENAME} !\.(gif|jpg|png|svg|jpeg|pdf|zip|css|js)$ [NC]
RewriteRule ^(.*)$ https://%{HTTP_HOST}/$1/ [L,R=301]
```

Any help would be appreciated

**Comment by mzur** [comment]
The `POST` request is probably lost because there is a redirect from the URL without trailing slash to the URL with trailing slash. Try this as action URL: `<?= $page->url()?>/#hireus`.

If this doesn't work, is there anything else missing from the action URL that you "enforce" and that might result in a redirect?

**Comment by HashandSalt** [comment]
Bingo! Adding the slash to the form action work. Thank you, good spot.
