### ISSUE TITLE
ini_restore() Error

### ISSUE THREAD

**Issue by mightybart** [mzur/kirby-uniform#150]
Hello, I'm having troubles with this error message:

**There was an error sending the form: ini_restore() has been disabled for security reasons**

The form works fine, I'm recieving email with form data, but instead of success message I get this error message. Localhost is fine, I get this error only on live site. Any ideas how to solve this? Except enabling ini_restore()? 🤔 

Thanks!

**Comment by mzur** [comment]
The cause is most probably [this line](https://github.com/getkirby/toolkit/blob/d492775a8bcc0c2770f60b4df7bb4ee0abdb41a8/lib/email.php#L197) in the email class of the Kirby Toolkit. I don't think they can easily change that behavior but you could ask in their repository. Alternatively you could use some other email service like one using [PHPMailer](https://forum.getkirby.com/t/contact-form-with-phpmailer-uniform/6469).
