### ISSUE TITLE
How can i add uploaded files as attachments to the email

### ISSUE THREAD

**Issue by lareusmedia** [mzur/kirby-uniform#169]
i tried something like

`'attachments' => [
   'assets/images/favicon.png',
   $form->data('filefield'),
 ],`

but it didnt work. There is this error:

<img width="605" alt="bildschirmfoto 2019-01-17 um 18 37 34" src="https://user-images.githubusercontent.com/25037153/51337295-fdf2d300-1a86-11e9-8930-635c4912b027.png">

So how can i add uploaded files as attachments to the email?

**Comment by lareusmedia** [comment]
The added favicon to the mail is sent as attachment, but not the uploaded file.

**Comment by lareusmedia** [comment]
<img width="1203" alt="bildschirmfoto 2019-01-20 um 09 16 33" src="https://user-images.githubusercontent.com/25037153/51436799-3ddad580-1c94-11e9-9b4d-9c684ffb689b.png">

Unfortunately not, but the tmp_name in the array has obiously an error (red arrow in the screenshot)

**Comment by mzur** [comment]
You could:
- Use `move_uploaded_file` to move the file to a temporary location with the updated filename, send it via email and then delete it.
- Use the Uniform upload action to move the file to a temporary location, send it and then delete it.
- Open a pull request to Kirby that implements the second argument of `addAttachment` [here](https://github.com/getkirby/kirby/blob/72f01eac0a7db59360894e0cfb44680276260174/src/Email/PHPMailer.php#L56) so that you can choose a different file name for the attachment.

**Comment by mzur** [comment]
Please reopen if this is still relevant.
