### ISSUE TITLE
Uniform & File Cache

### ISSUE THREAD

**Issue by clamey** [mzur/kirby-uniform#45]
Hiya,

I'm seeing a problem with Uniform and Kirby's file cache.  I have several pages using the same template with a form on it.  When cache is enabled, the forms don't work.  When cache is disabled, the forms are fine.

I saw a thread in the Kirby forum about how this is a known issue, but I don't see any bugs open against it here.

So, I'm wondering if this is a known thing, and if so, is it a Kirby or Uniform issue?

Cheers,
topher

**Comment by mzur** [comment]
I would guess this is a Kirby issue and not quite a bug. The cache stores the rendered HTML of the page and Kirby serves the HTML instead of rendering the page again for each request. Doing this, the page controller and every other PHP code isn't touched (hence the speedup) so Uniform can't work. Try [disabling the cache](http://getkirby.com/docs/advanced/caching#ignoring-pages) for pages with dynamic functions like Uniform.

**Comment by clamey** [comment]
Yea, I think you are correct.  I'm trying to come up with a route to disable cache for all POSTs to keep all the GET requests performant.

**Comment by clamey** [comment]
Well, that was a bust since the cache.ignore applies to all HTTP methods.  I'll just disable the cache on a per-URI for now, but that's very fragile (editors can create/move things around on their own).
