### ISSUE TITLE
"Invalid reply address" on new kirby 2.1.0

### ISSUE THREAD

**Issue by dsply** [mzur/kirby-uniform#46]
"Invalid reply address"

Toolkit version: 2.1.0
Version de Kirby : 2.1.0
Version du Panel : 2.1.0

**Comment by mzur** [comment]
This is a bug with the `filter_var` function that doesn't accept email address like `Test User <user@example.com>` as a valid address (although they are). Since the toolkit [doesn't extract the email address](https://github.com/getkirby/toolkit/commit/4a686fbb58f6568957a9d9159ebaf2fb24bb60aa) anymore, the whole address is passed on to the validator function and validation will fail. I'll look into this.

Uniform will continue to work with Toolkit `v2.0.6`, though.

**Comment by malvese** [comment]
This made my day! I was pulling my hair with the invalid reply address, when I saw this issue and a commit with a fix about 4 hours before I found it :) Thank you for such a quick fix.
