### ISSUE TITLE
Trim feedback message

### ISSUE THREAD

**Issue by mzur** [mzur/kirby-uniform#64]
The [newlines of the feedback messages](https://github.com/mzur/kirby-uniform/blob/e9665b518d0e7d87bfd3fba716e6426ddf13850c/uniform/lib/UniForm.php#L451) produce excess whitespace and should be trimmed.

**Comment by rhawbert** [comment]
I'd like to help but I don't know how to pull request. So I'll contextualize our email conversation here. 

On my use case I've trimmed the message manually. Because I was using the form->message() returns to match a separate array's index in order to show more elaborated feedback messages in my template.

```php
trim($form->message())
```
The related line of code is probably this one:
https://github.com/mzur/kirby-uniform/blob/master/uniform/lib/UniForm.php#L451

**Comment by mzur** [comment]
@rhawbert Actually the `trim` needs to be insertes in [this line](https://github.com/mzur/kirby-uniform/blob/e9665b518d0e7d87bfd3fba716e6426ddf13850c/uniform/lib/UniForm.php#L459). If you like to try again with the pull request, fork this repository, clone your fork, apply the changes, commit and push them back to GitHub and then [create a pull request](https://help.github.com/articles/creating-a-pull-request/) from your fork to the `v2.2` branch of this repository. Good luck ;-)

**Comment by rhawbert** [comment]
This will be a fun adventure... bear with me, I'll try again :-)
