### ISSUE TITLE
Input file validation

### ISSUE THREAD

**Issue by illycz** [mzur/kirby-uniform#92]
Can you help me within file input validation (size and type)? How can I include that to uniform messages?

Thank a lot :)

**Comment by illycz** [comment]
Example: upload max. 5MB files and only images. When  i try upload something larger or different uniform don't send email, only echo messages.

Sorry for english :)

Patrik

**Comment by mzur** [comment]
Okay, so you have the upload action described in #73 and want to upload a file first and then send an email.

Currently, all actions are executed no matter if any of them failed (this will change with #93). So if your upload action failed, the email action will still be executed. As a workaround, you might implement an `upload-email` action that performs the file upload first and then calls the email action [like this](https://github.com/mzur/kirby-uniform/blob/f139a44cb49e5ab505c3134698c7fa2dcf4cda8a/uniform/actions/email-select.php#L27) if the upload was successful.

For restricting the file size and type you can do it like [this SO answer](http://stackoverflow.com/a/9153419/1796523). This must be done for every file in the `foreach ($actionOptions['files'] as $field)` loop. Instead of returning the error messages as a JS popup, you can return them as the `message` of the action.
